import React, { useState } from 'react';
import { Calendar, Clock, Download, RefreshCw, Share2, Sparkles } from 'lucide-react';
import { generateTimetable } from '../services/api';
import { motion } from 'framer-motion';
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable"; // Updated import

export const TimetableGenerator = () => {
  const [prompt, setPrompt] = useState('');
  const [schedule, setSchedule] = useState(null);
  const [loading, setLoading] = useState(false);

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    setLoading(true);
    try {
      const res = await generateTimetable(prompt);
      if (res.data.success) {
        setSchedule(res.data.timetable.schedule);
      }
    } catch (error) {
      console.error("Failed to generate timetable", error);
    }
    setLoading(false);
  };

  const downloadPDF = () => {
    if (!schedule) return;
    
    try {
      const doc = new jsPDF();
      
      // Add Title
      doc.setFontSize(18);
      doc.text("My AI Study Timetable", 14, 15);
      doc.setFontSize(11);
      doc.setTextColor(100);
      doc.text(`Generated on ${new Date().toLocaleDateString()}`, 14, 22);
      
      const tableData = [];
      schedule.forEach(day => {
        if (day.slots && Array.isArray(day.slots)) {
            day.slots.forEach(slot => {
                tableData.push([day.day, slot.time, slot.activity, slot.type]);
            });
        }
      });

      // Use autoTable function directly
      autoTable(doc, {
        startY: 30,
        head: [['Day', 'Time', 'Activity', 'Type']],
        body: tableData,
        theme: 'grid',
        headStyles: { fillColor: [79, 70, 229] }, // Indigo
        styles: { fontSize: 10, cellPadding: 3 },
        columnStyles: {
            0: { fontStyle: 'bold', width: 30 },
            1: { width: 35 },
            2: { width: 'auto' },
            3: { width: 25 }
        },
        didDrawPage: function (data) {
            // Footer
            doc.setFontSize(8);
            doc.text('Generated by EduLink AI', data.settings.margin.left, doc.internal.pageSize.height - 10);
        }
      });

      doc.save("EduLink_Timetable.pdf");
    } catch (error) {
      console.error("PDF Generation Error:", error);
      alert("Could not generate PDF. Please ensure jspdf and jspdf-autotable are installed.");
    }
  };

  const shareTimetable = () => {
    alert("Sharing functionality coming soon! (Integration with Email/WhatsApp)");
  };

  return (
    <div className="space-y-8 pb-10">
      <div className="flex items-center gap-3">
        <div className="p-3 bg-indigo-100 rounded-xl text-indigo-600">
          <Calendar size={32} />
        </div>
        <div>
          <h1 className="text-3xl font-bold text-gray-900">AI Timetable Generator</h1>
          <p className="text-gray-500">Describe your routine, and let AI organize your life.</p>
        </div>
      </div>

      {/* Input Section */}
      <div className="glass-card p-6 rounded-3xl shadow-lg">
        <textarea
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder="E.g., I have college from 9 AM to 4 PM. I want to study DSA and OS for 2 hours each daily. I go to the gym at 6 PM. My exam is in 2 months."
          className="w-full h-32 p-4 rounded-xl border border-gray-200 focus:ring-2 focus:ring-indigo-500 outline-none resize-none text-gray-700 bg-gray-50"
        />
        <div className="mt-4 flex justify-end">
          <button
            onClick={handleGenerate}
            disabled={loading}
            className="flex items-center gap-2 px-6 py-3 bg-indigo-600 text-white rounded-xl font-bold hover:bg-indigo-700 transition disabled:opacity-50 shadow-md"
          >
            {loading ? <RefreshCw className="animate-spin" size={20} /> : <Sparkles size={20} />}
            {loading ? "Generating..." : "Generate Timetable"}
          </button>
        </div>
      </div>

      {/* Timetable Grid */}
      {schedule && (
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="space-y-6"
        >
          <div className="flex justify-between items-center">
            <h2 className="text-xl font-bold text-gray-800">Your Weekly Schedule</h2>
            <div className="flex gap-2">
              <button onClick={handleGenerate} className="p-2 text-gray-500 hover:bg-gray-100 rounded-lg transition" title="Regenerate">
                <RefreshCw size={20} />
              </button>
              <button onClick={downloadPDF} className="p-2 text-gray-500 hover:bg-gray-100 rounded-lg transition" title="Download PDF">
                <Download size={20} />
              </button>
              <button onClick={shareTimetable} className="p-2 text-gray-500 hover:bg-gray-100 rounded-lg transition" title="Share">
                <Share2 size={20} />
              </button>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-7 gap-4 overflow-x-auto pb-4">
            {schedule.map((day, idx) => (
              <div key={idx} className="min-w-[200px] md:min-w-0 bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden flex flex-col h-full">
                <div className="bg-indigo-50 p-3 text-center font-bold text-indigo-700 border-b border-indigo-100">
                  {day.day}
                </div>
                <div className="p-2 space-y-2 flex-1">
                  {day.slots.map((slot, sIdx) => (
                    <div 
                      key={sIdx} 
                      className={`p-2 rounded-xl text-xs border-l-4 shadow-sm ${
                        slot.type === 'study' ? 'bg-blue-50 border-blue-500 text-blue-700' :
                        slot.type === 'busy' ? 'bg-gray-50 border-gray-400 text-gray-600' :
                        slot.type === 'break' ? 'bg-green-50 border-green-400 text-green-700' :
                        'bg-purple-50 border-purple-400 text-purple-700'
                      }`}
                    >
                      <div className="flex items-center gap-1 font-bold mb-1 opacity-80">
                        <Clock size={10} /> {slot.time}
                      </div>
                      <div className="font-semibold leading-tight">{slot.activity}</div>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </motion.div>
      )}
    </div>
  );
};
